# Generated by Django 3.1.5 on 2021-03-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.SmallIntegerField()),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.TextField()),
                ('image', models.ImageField(upload_to='spell/images')),
                ('spell_type', models.CharField(choices=[('AR', 'Arcana'), ('DI', 'Divina'), ('UN', 'Universal')], max_length=2)),
                ('school', models.CharField(choices=[('AB', 'Abjuração'), ('AD', 'Advinhação'), ('CO', 'Convocação'), ('EN', 'Encantamento'), ('EV', 'Evocação'), ('IL', 'Ilusão'), ('NE', 'Necromancia'), ('TR', 'Transmutação')], max_length=2)),
                ('circle', models.SmallIntegerField()),
                ('execution', models.TextField()),
                ('range', models.TextField()),
                ('target_area_effect', models.TextField()),
                ('duration', models.TextField()),
                ('resistance', models.TextField(blank=True)),
            ],
        ),
    ]
