# Generated by Django 3.1.5 on 2021-03-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='spell',
            name='image',
            field=models.ImageField(blank=True, upload_to='spell/images'),
        ),
    ]
