# Generated by Django 3.1.5 on 2021-03-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0003_auto_20210306_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='spell_name',
            new_name='name',
        ),
    ]
