# Generated by Django 3.1.5 on 2021-03-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0004_auto_20210306_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='enhancements',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spell', to='spell.enhancement'),
        ),
    ]
