# Generated by Django 3.1.5 on 2021-03-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0005_spell_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='enhancements',
        ),
        migrations.AddField(
            model_name='enhancement',
            name='spell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spell.spell'),
        ),
    ]
