# Generated by Django 3.0.5 on 2021-03-08 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spell', '0008_auto_20210308_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='book_magazine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spell',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spell',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
