# Generated by Django 3.0.5 on 2021-03-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0009_auto_20210308_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grimoire',
        ),
    ]
