# Generated by Django 3.0.5 on 2021-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0010_delete_grimoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='circle',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=1),
        ),
    ]
