# Generated by Django 3.0.5 on 2021-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0011_auto_20210320_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancement',
            name='cost',
            field=models.CharField(max_length=30),
        ),
    ]
