# Generated by Django 3.0.5 on 2021-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0012_auto_20210322_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='sorting_name',
            field=models.TextField(blank=True),
        ),
    ]
