# Generated by Django 3.1.5 on 2026-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0013_spell_sorting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='shared_users',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='cost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(choices=[('AB', 'Abjuração'), ('AD', 'Adivinhação'), ('CO', 'Convocação'), ('EN', 'Encantamento'), ('EV', 'Evocação'), ('IL', 'Ilusão'), ('NE', 'Necromancia'), ('TR', 'Transmutação')], default='AB', max_length=2),
        ),
    ]
